# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.

previous_term = 1
current_term = 2
even_sum = 0
term_sum = previous_term + current_term

while previous_term < 4000000:
    new_term = current_term + previous_term
    if previous_term % 2 == 0:
        even_sum = even_sum + previous_term
    previous_term = current_term
    current_term = new_term

print(even_sum)

